# This is a basic workflow to help you get started with Actions

name: todoapp hello CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main 
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  APP_NAME: tooapp-dagger-europa
  NETLIFY_TEAM: kansukeito

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dagger:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repository
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Deploy to Netlify
        uses: dagger/dagger-for-github@v2
        
        with:
          version: 0.2
          cmds: |
            project update
            do deploy
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

